#!/bin/sh
while read file
do
  case "$1" in
  "w") 	
    feh --no-fehbg --bg-fill "$file"
    killall dunst && dunst &
    killall dwm
    dwmblocks &
    pkill sxiv
    notify-send "Enjoy your new theme!" ;;

  "y")
    xclip -selection clipboard "$file" -t image/png &&
    notify-send "$file copied to clipboard!" ;;

  esac
done
